server.port: 9903

spring:
  config:
    use-legacy-processing: true
  application.name: client-service
  cloud.config:
    discovery:
      enabled: true
      serviceId: config-server
    fail-fast: true
    retry:
      initialInterval: 2000
      maxAttempts: 30
  mvc.servlet.load-on-startup: 1

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abolfazl
    password: Am311865186
    username: root

  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
    #preferIpAddress: true
